### ISSUE TITLE
Several tier1 test failed assertion in ShenandoahYoungGenMemoryPool::get_memory_usage()

### ISSUE THREAD

**Issue by zhengyu123** [corretto/corretto-17#30]
### Describe the bug
`# A fatal error has been detected by the Java Runtime Environment:`
`#`
`#  Internal Error (/home/zhengyu/ws/corretto-17/src/hotspot/share/gc/shenandoah/shenandoahMemoryPool.cpp:78), pid=2135199, tid=2135266`
`#  assert(initial <= max) failed: initial: 805306368, max: 268435456`
`#`

### To Reproduce
Run tier test with generational Shenandoah:
`make CONF=linux-x86_64-server-fastdebug run-test TEST=tier1 TEST_VM_OPTS=-XX:+UseShenandoahGC -XX:+UnlockExperimentalVMOptions -XX:ShenandoahGCMode=generational`

### Additional contex

[hs_err_pid2134734.log](https://github.com/corretto/corretto-17/files/7636008/hs_err_pid2134734.log)

**Comment by zhengyu123** [comment]
`OldGenMemoryPool` has similar problem:
`# A fatal error has been detected by the Java Runtime Environment:`
`#`
`#  Internal Error (/home/zhengyu/ws/corretto-17/src/hotspot/share/gc/shenandoah/shenandoahMemoryPool.cpp:110), pid=2132900, tid=2132950`
`#  assert(initial <= max) failed: initial: 805306368, max: 536870912`
`#`
`# JRE version: OpenJDK Runtime Environment (17.0.1) (fastdebug build 17.0.1-internal+0-adhoc.zhengyu.corretto-17)`
`# Java VM: OpenJDK 64-Bit Server VM (fastdebug 17.0.1-internal+0-adhoc.zhengyu.corretto-17, mixed mode, tiered, compressed oops, compressed class ptrs, shenandoah gc, linux-amd64)`
`# Problematic frame:`
`# V  [libjvm.so+0x19178e3]  ShenandoahOldGenMemoryPool::get_memory_usage()+0x163`
`

**Comment by alvdavi** [comment]
This should 've been solved by #31

**Comment by zhengyu123** [comment]
Pull the latest and still seeing them ...

e.g. `jdk/javadoc/doclet/testDocLintOption/TestDocLintOption.java` still failed.

`#`
`# A fatal error has been detected by the Java Runtime Environment:`
`#`
`#  Internal Error (/home/zhengyu/ws/corretto-17/src/hotspot/share/gc/shenandoah/shenandoahMemoryPool.cpp:110), pid=2133610, tid=2133669`
`#  assert(initial <= max) failed: initial: 805306368, max: 536870912`
`#`
`# JRE version: OpenJDK Runtime Environment (17.0.1) (fastdebug build 17.0.1-internal+0-adhoc.zhengyu.corretto-17)`
`# Java VM: OpenJDK 64-Bit Server VM (fastdebug 17.0.1-internal+0-adhoc.zhengyu.corretto-17, mixed mode, tiered, compressed oops, compressed class ptrs, shenandoah gc, linux-amd64)`
`# Problematic frame:`
`# V  [libjvm.so+0x19178e3]  ShenandoahOldGenMemoryPool::get_memory_usage()+0x163`
`#`
`# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /home/zhengyu/ws/corretto-17/build/linux-x86_64-server-fastdebug/test-support/jtreg_test_langtools_tier1/scratch/2/core.2133610)`
`#`

**Comment by zhengyu123** [comment]
Yes, it seems to work with latest pull.
